services:

  mysql:
    image: mysql:8.0.43
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salessavvy_db
    ports:
      - "3308:3306"
    volumes:
      - salessavvy_mysql_data:/var/lib/mysql
      - ./Sales_Savvy_Database:/docker-entrypoint-initdb.d
    networks:
      - salessavvy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Sales_Savvy_Backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/salessavvy_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - salessavvy-network

  frontend:
    image: soumyajitparamanick96419/salessavvy-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - salessavvy-network

networks:
  salessavvy-network:

volumes:
  salessavvy_mysql_data:
